name: manhole_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_zxing: ^1.5.2
  firebase_core: ^2.27.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/man.png
    - assets/bg_login.png
