// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNcZ0vW2McLva8SSAsT7tAd0BZD-JiQ2A',
    appId: '1:71739860092:web:2ea52dce1d9020e987d5f9',
    messagingSenderId: '71739860092',
    projectId: 'salon-booking-5ea0c',
    authDomain: 'salon-booking-5ea0c.firebaseapp.com',
    databaseURL: 'https://salon-booking-5ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'salon-booking-5ea0c.appspot.com',
    measurementId: 'G-3CX91RJX15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffcknN-RwS2gyhQEdaij93BnyV46zgrw',
    appId: '1:71739860092:android:7103d2efb32c991687d5f9',
    messagingSenderId: '71739860092',
    projectId: 'salon-booking-5ea0c',
    databaseURL: 'https://salon-booking-5ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'salon-booking-5ea0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_SOoE_Y9UbGx5NifPTI-NfjDY6cTGKZw',
    appId: '1:71739860092:ios:8c39141637f39ddd87d5f9',
    messagingSenderId: '71739860092',
    projectId: 'salon-booking-5ea0c',
    databaseURL: 'https://salon-booking-5ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'salon-booking-5ea0c.appspot.com',
    iosClientId: '71739860092-igp8pbug72nt5is6svdqerbm3ttp2c6m.apps.googleusercontent.com',
    iosBundleId: 'com.man.vin.manholeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_SOoE_Y9UbGx5NifPTI-NfjDY6cTGKZw',
    appId: '1:71739860092:ios:8c39141637f39ddd87d5f9',
    messagingSenderId: '71739860092',
    projectId: 'salon-booking-5ea0c',
    databaseURL: 'https://salon-booking-5ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'salon-booking-5ea0c.appspot.com',
    iosClientId: '71739860092-igp8pbug72nt5is6svdqerbm3ttp2c6m.apps.googleusercontent.com',
    iosBundleId: 'com.man.vin.manholeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNcZ0vW2McLva8SSAsT7tAd0BZD-JiQ2A',
    appId: '1:71739860092:web:5ccab39e3638e42187d5f9',
    messagingSenderId: '71739860092',
    projectId: 'salon-booking-5ea0c',
    authDomain: 'salon-booking-5ea0c.firebaseapp.com',
    databaseURL: 'https://salon-booking-5ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'salon-booking-5ea0c.appspot.com',
    measurementId: 'G-HJ72SF4XK1',
  );
}
